### ISSUE TITLE
Disallow unauthenticated requests for privileged endpoints

### ISSUE THREAD

**Issue by HalosGhost** [mit-dci/opencbdc-ui#10]
The `mintTx` endpoint is incredibly privileged operation. Right now, there's no restriction on interacting with that interface. **This is unacceptable for a production-grade deployment.**

Given the intended use-case this repository is exploring (unprivileged, non-custodied wallet providers), such an interface likely shouldn't/wouldn't actually exist in a productionized fork/recreation of this project. However, some variant of endpoint authentication would not go amiss, to make sure no one gets the wrong idea.

_Originally posted by @anders94 in https://github.com/mit-dci/opencbdc-ui/pull/6#discussion_r1739276163_

**Comment by HalosGhost** [comment]
Note: this also requires some level of authentication to be present in the running equivalent of [`opencbdc-tx`](https://github.com/mit-dci/opencbdc-tx) because authentication of privileged operations should be strict and verified (at least) at the boundaries of the security perimeter (which this repository sits outside).

cf. https://github.com/mit-dci/opencbdc-tx/issues/98

**Comment by anders94** [comment]
This might be duplicated in https://github.com/mit-dci/opencbdc-ui/issues/7 and https://github.com/mit-dci/opencbdc-ui/issues/8

**Comment by HalosGhost** [comment]
closing as a duplicate of already-open issues.
